language: node_js
node_js:
   - "0.12.7"

branches:
  only:
    - master
    - dev
script:
  make riot test-compiler

sudo: false

before_install:
  npm install babel && npm install jade && npm install coffee-script && npm install

after_success:
  make test-sauce && make test-coveralls

notifications:
    email: false
